keep-open
vo=gpu-next
profile=gpu-hq
hwdec=auto
volume-max=300
video-stereo-mode=no
ao=pulse
af=lavfi="pan=stereo|FL < 0.5*FC + 0.3*FLC + 0.3*FL + 0.3*BL + 0.3*SL + 0.5*LFE | FR < 0.5*FC + 0.3*FRC + 0.3*FR + 0.3*BR + 0.3*SR + 0.5*LFE",lavfi="acompressor=10"
no-keepaspect-window
autofit-larger=1280x720
