[config]

[templates.kvantum_kvconfig]
input_path = "~/.config/matugen/templates/kvantum-colors.kvconfig"
output_path = "~/.config/Kvantum/matugen/matugen.kvconfig"

[templates.kvantum_svg]
input_path = "~/.config/matugen/templates/kvantum-colors.svg"
output_path = "~/.config/Kvantum/matugen/matugen.svg"
